export const projects = [
    {
        title: "Nexakun",
        description: "Account Game Store with responsive layout using Laravel 11 and Tailwind CSS",
        tech: ["Vite", "PHP", "Laravel", "Tailwind CSS", "MySQL"],
        link: "https://github.com/Fauzi-Taufiq/nexakun-accountstore.git",
        image: "/images/account-store-game.png",
        delay: 0,
    },
    {
        title: "Jogja Culinary",
        description: "A culinary website in Yogyakarta with a responsive layout using React, Tailwind CSS, and MySQL",
        tech: ["Vite", "Javascript", "React", "Tailwind CSS", "Node.js", "MySQL"],
        link: "https://github.com/rizkicahyaa/jogja-culinary",
        image: "/images/jogja-culinary.png",
        delay: 100,
    },
    {
        title: "Roomoria",
        description: "Roomoria is a modern hotel booking website built using React, TypeScript, and Tailwind CSS.",
        tech: ["Vite", "Typescript", "React", "Tailwind CSS"],
        link: "https://github.com/rizkicahyaa/roomoria",
        demo: "https://roomoria.vercel.app",
        image: "/images/roomoria.png",
        delay: 200,
    },
    {
        title: "MuseGuide",
        description: "A museum recommendation website in Yogyakarta using React, Tailwind CSS, Node.js and MySQL",
        tech: ["Vite", "Typescript", "React", "Tailwind CSS", "Node.js", "MySQL"],
        link: "https://github.com/rizkicahyaa/fe-museguide",
        demo: "https://museguide.vercel.app",
        image: "/images/museguide.png",
        delay: 300,
    },
    {
        title: "MiraiNime",
        description: "MiraiNime is a simple website that utilizes the Jikan API to display anime information from MyAnimeList.",
        tech: ["Vite", "Typescript", "React", "Tailwind CSS"],
        link: "https://github.com/rizkicahyaa/mirai-nime",
        demo: "https://mirainime.vercel.app",
        image: "/images/mirainime.png",
        delay: 400,
    },
    {
        title: "Focsy",
        description: "A productivity timer web application that helps you stay focused, manage your time, and get more done (pomodoro).",
        tech: ["Vite", "Typescript", "React", "Tailwind CSS"],
        link: "https://github.com/rizkicahyaa/focsy",
        demo: "https://focsy.vercel.app",
        image: "/images/focsy-2.png",
        delay: 500,
    },
    {
        title: "ClaireBlog",
        description: "A blog creation system with a responsive layout using PHP, MySQL, Tailwind CSS, and Docker",
        tech: ["PHP", "Tailwind CSS", "MySQL", "Docker"],
        link: "https://github.com/rizkicahyaa/ClaireBlog",
        image: "/images/blog-system.png",
        delay: 600,
    },
    {
        title: "MovieTix",
        description: "A web-based cinema ticket booking system using PHP and MySQL.",
        tech: ["PHP", "Bootstrap", "MySQL"],
        link: "https://github.com/Fauzi-Taufiq/bioskop",
        image: "/images/cinema-ticket-booking.png",
        delay: 700,
    },
    {
        title: "NgaduClaire",
        description: "Web apps public complaints system using PHP and MySQL.",
        tech: ["PHP", "Bootstrap", "MySQL"],
        link: "https://github.com/rizkicahyaa/ngadu-claire",
        image: "/images/public-complaint.png",
        delay: 800,
    },
    {
        title: "Lost Lantern Studio",
        description: "Landing page studio game using HTML, Tailwind CSS, and AOS.",
        tech: ["HTML", "Tailwind CSS"],
        link: "https://github.com/rizkicahyaa/lostlantern-page",
        demo: "https://lostlantern.netlify.app",
        image: "/images/lost-lantern.png",
        delay: 900,
    },
    {
        title: "Ngawikerto Hotel Ticket Booking System (UI/UX)",
        description: "A mobile-based hotel ticket booking system prototype using Figma.",
        tech: ["Figma"],
        link: "https://www.figma.com/design/eSa9brf8IkddzMcMuTHBG2/Sistem-Pemesanan-Tiket-Hotel?node-id=0-1&t=K0ksMtmmtNOVZMN9-1",
        image: "/images/hotel-booking-uiux.png",
        delay: 1000,
    },
    {
        title: "PayCuan E-Wallet (UI/UX)",
        description: "A mobile-based e-wallet application prototype using Figma.",
        tech: ["Figma"],
        link: "https://www.figma.com/design/kW5uDRZwaYyAR7339g3jhz/Mockup-Sistem-E-Wallet--PayCuan-?node-id=119-3&t=tugfB4IN6ZLYsd4h-1",
        image: "/images/paycuan.png",
        delay: 1100,
    },
];
